### ISSUE TITLE
"allocWideCString" not declared.

### ISSUE THREAD

**Issue by vegberg** [Vladar4/libtcod-nim#1]
c:\users\ransel\.babel\pkgs\libtcod-nim-0.95.1\libtcod\console.nim(218, 22) Info: instantiation from here
    c:\users\ransel\.babel\pkgs\libtcod-nim-0.95.1\libtcod\console.nim(211, 6) Error: undeclared identifier: 'allocWideCString'
Getting this error when trying to compile on Windows.

**Comment by Vladar4** [comment]
This should be fixed by 2f337a57be82cb656ad0840654db69547d2d27db
